language: objective-c
osx_image: xcode11.1
env:
  matrix:
  - TEST_PLATFORM="platform=iOS Simulator,OS=13.1,name=iPhone 8"
  global:
    secure: H45yyUlB0cXQrzTTcnmD3WrkCyqjUzaop2jHgmBF3bm8ue4XOcTWKDSDcAN39SG0FUeDC7GdDCtWAc3VCpLwN++5IznAnvBuZSGgxQ2lCxWMhdTtXtOWU2mivgVvs+uldS7/TuVlOjZ7inrTgetl+jgFjenwESOGIIZwn7SXpPo=
rvm:
    - 2.3.7
before_install:
    - gem install slather
    - gem install xcpretty -N --no-document
    - gem install cocoapods -v '1.5.3'
install:
    - ./.travis/install.sh
script: ./.travis/test.sh
after_success: slather
